name: Nowoczesny Zarządca Nieruchomości
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "/artykuly:num/"
defaults:
  -
    scope:
      path: ""
    values:
      author: Michał Ziemski
      lang: pl

